Traceback (most recent call last):
  File "/Users/federicocirett/Documents/GitHub/kefir_ajuste/.venv/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/federicocirett/Documents/GitHub/kefir_ajuste/.venv/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/federicocirett/Documents/GitHub/kefir_ajuste/.venv/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/federicocirett/Documents/GitHub/kefir_ajuste/.venv/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/federicocirett/Documents/GitHub/kefir_ajuste/.venv/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/federicocirett/Documents/GitHub/kefir_ajuste/.venv/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/federicocirett/Documents/GitHub/kefir_ajuste/.venv/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from scipy.integrate import odeint
import numpy as np



def log_dif_eq(y:float,x:None,r:float=0.01,k:float=100)->float:
    return r*y*(1-y/k)

def analytic_sol(y0:float,interval:tuple,r:float=0.01,k:float=100)->list:
    x_values = np.linspace(interval[0], interval[1], 1000)
    curve = [  ( x, y0* k / (y0 + (k - y0) * np.exp(- r * x)) ) for x in x_values]
    return curve



def runge_kutta(f,y0:float,interval:tuple,n:int=10)->list:
    x=interval[0]
    h=(interval[1]-interval[0])/n
    y_est=y0
    curve=[]
    for i in range(1,n+1):
        k1=h*f(x=x,y=y_est)
        k2=h*f(x=x+h/2,y=y_est+k1/2)
        k3=h*f(x=x+h/2,y=y_est+k2/2)
        k4=h*f(x=x+h,y=y_est+k3)

        # Add point to curve
        curve.append( ( x, y_est) )

        # Update
        y_est+=(k1+2*k2+2*k3+k4)/6
        x+=h
    return curve


------------------


[31m---------------------------------------------------------------------------[39m
[31mModuleNotFoundError[39m                       Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[1][39m[32m, line 1[39m
[32m----> [39m[32m1[39m [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01mscipy[39;00m[34;01m.[39;00m[34;01mintegrate[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m odeint
[32m      2[39m [38;5;28;01mimport[39;00m[38;5;250m [39m[34;01mnumpy[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[34;01mnp[39;00m
[32m      6[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34mlog_dif_eq[39m(y:[38;5;28mfloat[39m,x:[38;5;28;01mNone[39;00m,r:[38;5;28mfloat[39m=[32m0.01[39m,k:[38;5;28mfloat[39m=[32m100[39m)->[38;5;28mfloat[39m:

[31mModuleNotFoundError[39m: No module named 'scipy'

